### PR TITLE
lock typescript version to 4.7

### PR DESCRIPTION
**Pull request by nksfrank**
locking typescript version to `4.7.x` to resolve issue #370 where typescript@4.8 seems to have changed their API by removing the `ts.sys.fileExists` function that is used in this package.

### CODE REVIEW

**Comment by js2me** [comment]
@all-contributors please add @nksfrank for code, bugs

**Comment by js2me** [comment]
@nksfrank thanks!

**Comment by js2me** [comment]
@nksfrank please reopen PR with this fix from the `next` branch .   
Because currently PR has conflicted changes.   
Just better to do that is checkout to next , pull all changes, cherry pick 5b51bf1dcb19fe1573d946c1d3fc34902f6dfe80 and create PR.

**Comment by nksfrank** [comment]
alright, I'll move it over to the `next` branch

**Pull request closed without merging**
