### PR TITLE
lock typescript version

### PR DESCRIPTION
**Pull request by nksfrank**
locking typescript version to `4.7.x` to resolve issue #370 where typescript@4.8 seems to have changed their API by removing the `ts.sys.fileExists` function that is used in this package.

### CODE REVIEW

**Review by shreypdev — APPROVED** [review]
🚀

**Comment by shreypdev** [comment]
When will this be published in new version?

**Comment by VitaliKhileuski** [comment]
> When will this be published in new version?

+1

**Comment by nksfrank** [comment]
closing in favour of #405

**Pull request closed without merging**
