### PR TITLE
fix: handling for content-type application/json with a charset parameter

### PR DESCRIPTION
**Pull request by JochenDiekenbrock**
Fixes acacode/swagger-typescript-api#440

### CODE REVIEW

**Comment by JochenDiekenbrock** [comment]
I did not really understand the tests structure. If the test I have added should be written differently, please advise.

**Comment by js2me** [comment]
@JochenDiekenbrock Hi, thanks for your PR, please change target branch to `next`

**Comment by JochenDiekenbrock** [comment]
Sorry, it was a long day. After this is merged, I will have a look at #312 and will open another PR.

**Comment by JochenDiekenbrock** [comment]
npm run prepare produced no changes.

**Comment by js2me** [comment]
@JochenDiekenbrock thank you for your contributions!

**Comment by js2me** [comment]
@all-contributors please add @JochenDiekenbrock for code bugs

**Pull request merged**
