### PR TITLE
feat: add deprecated in more places

### PR DESCRIPTION
**Pull request by brookjordan**
Add deprecated jsdocs in more areas

### CODE REVIEW

**Comment by brookjordan** [comment]
@js2me does this look worth adding?

**Comment by hedgepigdaniel** [comment]
This is very useful, thanks @brookjordan!

**Comment by arical** [comment]
We've been caught out by deprecated properties a couple of times now and would really appreciate this functionality 😄

**Comment by jinkwon** [comment]
Very useful MR.

**Comment by js2me** [comment]
@brookjordan thank you for your PR!

**Comment by js2me** [comment]
@all-contributors please add @jinkwon for code

**Comment by brookjordan** [comment]
Out of interest, @js2me, did you add @jinkwon as a contributor by mistake?

**Comment by js2me** [comment]
@all-contributors please add @brookjordan for code

**Pull request merged**
