### PR TITLE
feat: add --extract-nested-objects option [issues/639]

### PR DESCRIPTION
**Pull request by frolovsky**
### Changes
New option `--extract-nested-objects` which parse interfaces recursivly. Related to https://github.com/acacode/swagger-typescript-api/issues/639

### Fixes
- add `extractResponses` to `index.d.ts` (for some reason, it wasn't there before)

### CODE REVIEW

**Comment by dl-ias** [comment]
Waiting for this feature.

**Comment by SmittyTint** [comment]
@smorimoto why was this branch closed? is there another way to handle this scenario?

**Comment by frolovsky** [comment]
When I created the pull revext project, it had looked abandoned for several months. As I understand it, my pull request, like some others, was closed due to the need to refactor. Now these improvements are not relevant, but I plan to restore them. I also want to say thank you for the refactoring. 
P.S. Like for TS and for the vitest (tests take 23 seconds instead of 3 minutes, @smorimoto thx)

**Comment by smorimoto** [comment]
@frolovsky We still have a lot of work to do, but thank you for your understanding 🙂

**Pull request closed without merging**
