### PR TITLE
added --unwrap-response-data to unwrap the data item from the response

### PR DESCRIPTION
**Pull request by laktak**
This is trying to solve #267.

Please let me know if this approach fits with your project.

### CODE REVIEW

**Comment by js2me** [comment]
Hello @laktak !   
Thanks for this PR with the nice feature!   
Please make changes for axios-http-client eta template too

**Comment by laktak** [comment]
@js2me I tried to add it according to the axios documentation.

I've tested the fetch implementation but I'm not using the axios client. Could you add some tests?

**Comment by Liugq5713** [comment]
@laktak forget to change index.d.ts file ?

**Comment by laktak** [comment]
> @laktak forget to modify index.d.ts file ?

Yes, I'm using the CLI version and did not notice that it had one.

**Pull request merged**
