### PR TITLE
Sort types

### PR DESCRIPTION
**Pull request by RoCat**
For some reasons sometimes swagger files swap their types and types properties order
e.g.
```
export interface Country {
  /** @format int64 */
  id?: number;

  /** @format double */
  latitude?: number;

  /** @format double */
  longitude?: number;
}
```

becames

```
export interface Country {
  /** @format int64 */
  id?: number;

  /** @format double */
  longitude?: number;

  /** @format double */
  latitude?: number;
}
```

I added a `sortTypes` params to avoid that and reorder types / types params alphabetically. The main goal is to avoid fake changes on commiting API files.

### CODE REVIEW

**Comment by RoCat** [comment]
it seems to answer the issue #151

**Comment by js2me** [comment]
Hello @RoCat ! Thank you for this cool feature request!

**Comment by NikYushchenko** [comment]
Hello. I caught one issue with the sort function.

`ERRRORR TypeError: schema.rawTypeData.$parsed.content.sort is not a function`
`'$parsed': {...schema.rawTypeData['$parsed'], content: schema.rawTypeData['$parsed'].content.sort(sortByName)}`

After some research I've found that in openapi we have this `"TriggerAPISchema": "title":"TriggerAPISchema","type":"object","properties":{}},`, which in the code above has `content: 'object'`, where `sort` is undefined.

What can we do in this case? 
I think it will be good to add validation `Array.isArray(schema.rawTypeData['$parsed'].content)`

image

**Comment by NikYushchenko** [comment]
Hello. I caught one issue with the sort function.

`ERRRORR TypeError: schema.rawTypeData.$parsed.content.sort is not a function`
`'$parsed': {...schema.rawTypeData['$parsed'], content: schema.rawTypeData['$parsed'].content.sort(sortByName)}`

After some research I've found that in openapi we have this `"TriggerAPISchema": "title":"TriggerAPISchema","type":"object","properties":{}},`, which in the code above has `content: 'object'`, where `sort` is undefined.

What can we do in this case? 
I think it will be good to add validation `Array.isArray(schema.rawTypeData['$parsed'].content)`

image

**Comment by js2me** [comment]
@all-contributors please add @RoCat for code ideas design

**Pull request merged**
